name: Run Basic Tests - Scheduler

on:
  schedule:
    - cron: '0 20 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install
        
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/**/*.cy.js
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        continue-on-error: true

      - name: upload relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Relatório
          path: |
            cypress/videos
            cypress/screenshots
          if-no-files-found: warn
