# nome da pipeline
name: Run Basic Tests

# momento que será executada
on: 
  pull_request:
    branches: [ master ]

jobs:
  #o que será feito nessa pipeline
  cypress-run:
    #maquina que será executada
    runs-on: ubuntu-latest

    steps:
    # clone do projeto
    - name: Checkout/Clone of project
      uses: actions/checkout@v3

    # execução e configuração no terminal
    -name: Run Tests
      uses: cypress-io/github-action@v5
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}